PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

INSERT {
  GRAPH ?gCommon {
    ?persoon a foaf:Person;
      mu:uuid ?uuidPersoon;
      foaf:member ?bestuurseenheid;
      foaf:firstName ?firstName;
      foaf:familyName ?familyName;
      foaf:account ?account.
    ?account a foaf:OnlineAccount;
      mu:uuid ?uuidAccount;
      ext:sessionGroup ?bestuurseenheid;
      foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service>;
      ext:sessionRole "Decide-gebruiker".
    ?bestuurseenheid a besluit:Bestuurseenheid ;
      mu:uuid ?uuidBestuurseenheid .
  }

  GRAPH ?gOrganization {
    ?bestuurseenheid
      <http://purl.org/dc/terms/identifier> "0207445287" ;
      <http://www.w3.org/ns/adms#identifier> ?identifier ;
      <http://www.w3.org/ns/regorg#legalName> "Buggenhout" ;
      <http://purl.org/dc/terms/identifier> "OVO002038" ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Buggenhout" ;
      <http://mu.semte.ch/vocabularies/ext/kbonummer> "0207445287" .

    ?identifier
      a <http://www.w3.org/ns/adms#Identifier> ;
      mu:uuid ?uuidIdentifier;
      <http://www.w3.org/2004/02/skos/core#notation> "SharePoint identificator" .
  }
}
WHERE {
    BIND(<http://mu.semte.ch/graphs/public> as ?gPublic)
    BIND(<http://mu.semte.ch/graphs/organizations/7d7122bd82f165e091a36c830d041b59aa48e4be9ea0aa06dc4c67ef381b7505> as ?gOrganization)
    VALUES ?gCommon {
      <http://mu.semte.ch/graphs/public>
      <http://mu.semte.ch/graphs/organizations/7d7122bd82f165e091a36c830d041b59aa48e4be9ea0aa06dc4c67ef381b7505>
    }

    BIND("a131fbc9-a78a-4c03-8dd3-bcd480c1810a" as ?uuidIdentifier)
    BIND(IRI(CONCAT("http://data.lblod.info/id/identificatoren/", ?uuidIdentifier)) as ?identifier)

    BIND("7d7122bd82f165e091a36c830d041b59aa48e4be9ea0aa06dc4c67ef381b7505" as ?uuidBestuurseenheid)
    BIND(IRI(CONCAT("http://data.lblod.info/id/bestuurseenheden/", ?uuidBestuurseenheid)) as ?bestuurseenheid)

    BIND("Jane" as ?firstName)
    BIND("Doe" as ?familyName)
    BIND(CONCAT(?familyName, ?firstName) as ?volledigeNaam)
    BIND(MD5(?volledigeNaam) as ?uuidPersoon)
    BIND(MD5(CONCAT(?volledigeNaam, "ACCOUNT")) as ?uuidAccount)
    BIND(IRI(CONCAT("http://data.lblod.info/id/persoon/", ?uuidPersoon)) AS ?persoon)
    BIND(IRI(CONCAT("http://data.lblod.info/id/account/", ?uuidAccount)) AS ?account)
}
