(in-package :mu-cl-resources)

(define-resource annotation ()
  :class (s-prefix "oa:Annotation")
  :properties `((:confidence :number ,(s-prefix "nif:confidence"))
                (:motivated-by :url ,(s-prefix "oa:motivatedBy")))
  :has-one `((specific-resource :via ,(s-prefix "oa:hasTarget")
                                :as "has-target")
             (location :via ,(s-prefix "oa:hasBody")
                       :as "has-body"))
  :features '(include-uri)
  :resource-base (s-url "http://data.lblod.info/id/annotations/")
  :on-path "annotations")

(define-resource specific-resource ()
  :class (s-prefix "oa:SpecificResource")
  :has-one `((expression :via ,(s-prefix "oa:hasSource")
                         :as "source")
             (text-position-selector :via ,(s-prefix "oa:hasSelector")
                                     :as "selector")
             (annotation :via ,(s-prefix "oa:hasTarget")
                         :as "annotations"
                         :inverse t))
  :features '(include-uri)
  :resource-base (s-url "http://data.lblod.info/id/specific-resources/")
  :on-path "specific-resources")

(define-resource text-position-selector ()
  :class (s-prefix "oa:TextPositionSelector")
  :properties `((:start :number ,(s-prefix "oa:start"))
                (:end :number ,(s-prefix "oa:end")))
  :features '(include-uri)
  :resource-base (s-url "http://data.lblod.info/id/text-position-selectors/")
  :on-path "text-position-selectors")
