(in-package :mu-cl-resources)

(defparameter *default-page-size* 20)
(defparameter *include-count-in-paginated-responses* t)
(defparameter sparql:*experimental-no-application-graph-for-sudo-select-queries* t)
(defparameter *fetch-all-types-in-construct-queries* t)
(defparameter *supply-cache-headers-p* t)
(defparameter *cache-count-queries* nil)
(defparameter *cache-model-properties* t)
(defparameter *max-group-sorted-properties* nil)
(setf *treat-uknown-literal-datatypes-from-sparql-as-string-p* t) ; langstrings seem to give problems?

(read-domain-file "user.lisp")
(read-domain-file "org.lisp")
(read-domain-file "eli.lisp")
(read-domain-file "eli-dl.lisp")
(read-domain-file "dcat.lisp")
(read-domain-file "annotation.lisp")
(read-domain-file "file.json")
(read-domain-file "log.json")
(read-domain-file "report.json")
(read-domain-file "harvest.json")
(read-domain-file "authentication.lisp")
(read-domain-file "master-scheduled-domain.lisp")
(read-domain-file "job.json")
(read-domain-file "geo.lisp")
