(define-resource legalExpression (expression)
  :class (s-prefix "eli:LegalExpression")
  :properties `((:jurisdiction :uri ,(s-prefix "eli:jurisdiction")))
  :resource-base (s-url "http://data.lblod.info/id/legal-expressions/")
  :features '(include-uri)
  :on-path "legal-expressions")

(define-resource complex-work (work)
  :class (s-prefix "eli:ComplexWork")
  :properties `((:title :string ,(s-prefix "eli:title"))
                (:identifier :string ,(s-prefix "dct:identifier"))
                (:date-document :date ,(s-prefix "eli:date_document"))
                (:work-type :url ,(s-prefix "eli:work_type"))
                (:consultation :url ,(s-prefix "oparl-temp:consultation"))
                (:license :string ,(s-prefix "oparl-temp:license"))
                (:keyword :string ,(s-prefix "oparl-temp:keyword"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:web :url ,(s-prefix "oparl-temp:web"))
                (:deleted :boolean ,(s-prefix "oparl-temp:deleted")))
  :has-one `((organization :via ,(s-prefix "eli:publisher")
                           :as "publisher"))
  :has-many `((complex-work :via ,(s-prefix "eli:refers_to")
                           :as "refers-to")
              (complex-work :via ,(s-prefix "eli:is_part_of")
                           :as "is-part-of")
              (complex-work :via ,(s-prefix "eli:has_part")
                           :as "parts")
              (work :via ,(s-prefix "eli:has_member")
                    :as "members")
              (expression :via ,(s-prefix "eli:is_realized_by")
                                      :as "is-realized-by")
              (location :via ,(s-prefix "oparl-temp:location")
                        :as "locations")
              (person :via ,(s-prefix "dct:creator")
                      :as "creators")
              (person :via ,(s-prefix "dct:contributor")
                      :as "contributors")
              (organization :via ,(s-prefix "dct:publisher")
                            :as "publishers")
              (organization :via ,(s-prefix "dct:creator")
                            :as "creators")
              (organization :via ,(s-prefix "dct:contributor")
                            :as "contributors"))
  :resource-base (s-url "http://data.lblod.info/id/complex-works/")
  :features '(include-uri)
  :on-path "complex-works")
