(in-package :mu-cl-resources)

(define-resource activity ()
  :class (s-prefix "eli-dl:Activity")
  :properties `((:activity-label :string ,(s-prefix "eli-dl:activity_label"))
                (:meeting-state :string ,(s-prefix "oparl-temp:meetingState"))
                (:cancelled :boolean ,(s-prefix "oparl-temp:cancelled"))
                (:activity-start-date :datetime ,(s-prefix "eli-dl:activity_start_date"))
                (:activity-end-date :datetime ,(s-prefix "eli-dl:activity_end_date"))
                (:activity-order :number ,(s-prefix "eli-dl:activity_order"))
                (:license :string ,(s-prefix "oparl-temp:license"))
                (:keyword :string ,(s-prefix "oparl-temp:keyword"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:web :url ,(s-prefix "oparl-temp:web"))
                (:deleted :boolean ,(s-prefix "oparl-temp:deleted"))
                (:had-activity-type :url ,(s-prefix "eli-dl:had_activity_type"))
                (:access-rights :uri ,(s-prefix "dct:accessRights")))
  :has-one `((location :via ,(s-prefix "vcard:hasLocality")
                       :as "has-locality"))
  :has-many `((organization :via ,(s-prefix "eli-dl:had_responsible_organization")
                            :as "had-responsible-organization")
              (person :via ,(s-prefix "eli-dl:had_participant_person")
                      :as "had-participant-person")
              (work :via ,(s-prefix "eli-dl:documented_by_a_realization_of")
                    :as "documented-by-a-realization-of")
              (work :via ,(s-prefix "eli-dl:recorded_in_a_realization_of")
                    :as "recorded-in-a-realization-of")
              (work :via ,(s-prefix "eli-dl:based_on_a_realization_of")
                    :as "based-on-a-realization-of")
              (foreseenActivity :via ,(s-prefix "eli-dl:consists_of")
                                :as "consists-of")
              (foreseenActivity :via ,(s-prefix "eli-dl:executed")
                                :as "executed")
              (participation :via ,(s-prefix "eli-dl:had_participation")
                           :as "had-participation")
              (vote :via ,(s-prefix "eli-dl:consists_of")
                    :as "consists-of")
              (processStage :via ,(s-prefix "eli-dl:occured_at_stage")
                            :as "occured-at-stage"))
  :resource-base (s-url "http://data.lblod.info/id/activities/")
  :features '(include-uri)
  :on-path "activities")

(define-resource legislativeProcess ()
  :class (s-prefix "eli-dl:LegislativeProcess")
  :resource-base (s-url "http://data.lblod.info/id/legislative-processes/")
  :features '(include-uri)
  :on-path "legislative-processes")

(define-resource legislativeProcessWork (work)
  :class (s-prefix "eli-dl:LegislativeProcessWork")
  :has-one `((organization :via ,(s-prefix "eli-dl:legislative_process_work_creator")
                           :as "legislative-process-work-creator"))
  :resource-base (s-url "http://data.lblod.info/id/legislative-process-works/")
  :features '(include-uri)
  :on-path "legislative-process-works")

(define-resource draftLegislationWork (legislativeProcess)
  :class (s-prefix "eli-dl:DraftLegislationWork")
  :resource-base (s-url "http://data.lblod.info/id/draft-legislation-works/")
  :features '(include-uri)
  :on-path "draft-legislation-works")

(define-resource parliamentaryTerm (organization)
  :class (s-prefix "eli-dl:ParliamentaryTerm")
  :resource-base (s-url "http://data.lblod.info/id/parliamentary-terms/")
  :features '(include-uri)
  :on-path "parliamentary-terms")

(define-resource participation ()
  :class (s-prefix "eli-dl:Participation")
  :properties `((:role :string ,(s-prefix "org:role"))
                (:voting-right :boolean ,(s-prefix "oparl-temp:votingRight"))
                (:license :string ,(s-prefix "oparl-temp:license"))
                (:keyword :string ,(s-prefix "oparl-temp:keyword"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:web :url ,(s-prefix "oparl-temp:web"))
                (:deleted :boolean ,(s-prefix "oparl-temp:deleted"))
                (:had-participation-role :url ,(s-prefix "eli-dl:had_participation_role")))
  :has-one `((person :via ,(s-prefix "org:member")
                     :as "person")
             (organization :via ,(s-prefix "org:organization")
                           :as "organization")
             (temporal :via ,(s-prefix "org:memberDuring")
                       :as "temporal")
             (organization :via ,(s-prefix "oparl-temp:onBehalfOf")
                           :as "on-behalf-of"))
  :has-many `((person :via ,(s-prefix "eli-dl:had_participant_person")
                     :as "had-participant-person")
              (organization :via ,(s-prefix "eli-dl:had_participant_organization")
                            :as "had-participant-organization"))
  :resource-base (s-url "http://data.lblod.info/id/participations/")
  :features '(include-uri)
  :on-path "participations")

(define-resource foreseenActivity (activity)
  :class (s-prefix "eli-dl:ForeseenActivity")
  :properties `((:notation :number ,(s-prefix "skos:notation"))
                (:result :string ,(s-prefix "oparl-temp:result")))
  :has-one `((activity :via ,(s-prefix "eli-dl:forms_part_of")
                       :as "forms-part-of"))
  :has-many `((work :via ,(s-prefix "eli-dl:based_on_a_realization_of")
                    :as "based-on-a-realization-of"))
  :resource-base (s-url "http://data.lblod.info/id/foreseen-activities/")
  :features '(include-uri)
  :on-path "foreseen-activities")

(define-resource decision (activity)
  :class (s-prefix "eli-dl:Decision")
  :properties `((:decision-outcome :uri ,(s-prefix "eli-dl:decision_outcome")))
  :resource-base (s-url "http://data.lblod.info/id/decisions/")
  :features '(include-uri)
  :on-path "decisions")

(define-resource vote (decision)
  :class (s-prefix "eli-dl:Vote")
  :properties `((:number-of-votes-favor :number ,(s-prefix "eli-dl:number_of_votes_favor"))
                (:number-of-votes-against :number ,(s-prefix "eli-dl:number_of_votes_against"))
                (:number-of-votes-abstention :number ,(s-prefix "eli-dl:number_of_votes_abstention")))
  :has-many `((activity :via ,(s-prefix "eli-dl:forms_part_of")
                        :as "forms-part-of")
              (person :via ,(s-prefix "eli-dl:had_voter_favor")
                      :as "had-voter-favor")
              (person :via ,(s-prefix "eli-dl:had_voter_against")
                      :as "had-voter-against")
              (person :via ,(s-prefix "eli-dl:had_voter_abstention")
                      :as "had-voter-abstention"))
  :resource-base (s-url "http://data.lblod.info/id/votes/")
  :features '(include-uri)
  :on-path "votes")

(define-resource processStage ()
  :class (s-prefix "eli-dl:ProcessStage")
  :resource-base (s-url "http://data.lblod.info/id/process-stages/")
  :features '(include-uri)
  :on-path "process-stages")