(in-package :mu-cl-resources)

(define-resource work ()
  :class (s-prefix "eli:Work")
  :properties `((:identifier :string ,(s-prefix "dct:identifier"))
                (:title :language-string ,(s-prefix "dct:title"))
                (:date-document :date ,(s-prefix "eli:date_document"))
                (:work-type :url ,(s-prefix "eli:work_type")))
  :has-many `((expression :via ,(s-prefix "eli:is_realized_by")
                          :as "is-realized-by")
              (document :via ,(s-prefix "eli:related_to")
                        :as "related-to")
              (organization :via ,(s-prefix "dct:creator")
                           :as "creator")
              (organization :via ,(s-prefix "eli:passed_by")
                           :as "passed-by")
              (organization :via ,(s-prefix "dct:contributor")
                           :as "contributor"))
  :features '(include-uri)
  :resource-base (s-url "http://data.lblod.info/id/works/")
  :on-path "works")

(define-resource expression ()
  :class (s-prefix "eli:Expression")
  :properties `((:title :language-string ,(s-prefix "eli:title"))
                (:language :uri ,(s-prefix "eli:language"))
                (:was-derived-from :url ,(s-prefix "prov:wasDerivedFrom"))
                (:expression-content :language-string ,(s-prefix "epvoc:expressionContent")))
  :has-one `((work :via ,(s-prefix "eli:is_realized_by")
                 :inverse t
                 :as "realizes"))
  :has-many `((manifestation :via ,(s-prefix "eli:is_embodied_by")
                           :as "is-embodied-by")
              (specific-resource :via ,(s-prefix "oa:hasSource")
                           :inverse t
                           :as "is-source-of")
              (annotation :via ,(s-prefix "oa:hasTarget")
                           :as "annotations"
                           :inverse t))
  :features '(include-uri)
  :resource-base (s-url "http://data.lblod.info/id/expressions/")
  :on-path "expressions")

(define-resource document () 
  :class (s-prefix "foaf:Document")
    :properties `((:label :string ,(s-prefix "rdfs:label"))
                (:file-name :string ,(s-prefix "oparl-temp:fileName"))
                (:media-type :string ,(s-prefix "eli:media_type"))
                (:issued :date ,(s-prefix "dct:issued"))
                (:byte-size :number ,(s-prefix "epvoc:byteSize"))
                (:see-also :url ,(s-prefix "rdfs:seeAlso"))
                (:license :string ,(s-prefix "oparl-temp:license"))
                (:keyword :string ,(s-prefix "oparl-temp:keyword"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:deleted :boolean ,(s-prefix "oparl-temp:deleted")))
  :features '(include-uri)
  :resource-base (s-url "http://data.lblod.info/id/documents/")
  :on-path "documents")

(define-resource manifestation (document)
  :class (s-prefix "eli:Manifestation")
  :properties `((:is-exemplified-by :url ,(s-prefix "eli:is_exemplified_by")))
  :features '(include-uri)
  :resource-base (s-url "http://data.lblod.info/id/manifestations/")
  :on-path "manifestations")