(in-package :mu-cl-resources)

(define-resource organization ()
  :class (s-prefix "org:Organization")
  :properties `((:pref-label :string ,(s-prefix "skos:prefLabel"))
                (:alt-label :string ,(s-prefix "skos:altLabel"))
                (:website :url ,(s-prefix "oparl-temp:website"))
                (:license :url ,(s-prefix "dct:license"))
                (:license-valid-since :datetime ,(s-prefix "oparl-temp:licenseValidSince"))
                (:oparl-since :datetime ,(s-prefix "oparl-temp:oparlSince"))
                (:identifier :string ,(s-prefix "dct:identifier"))
                (:see-also :url ,(s-prefix "rdfs:seeAlso"))
                (:consultation :url ,(s-prefix "oparl-temp:consultation"))
                (:file :url ,(s-prefix "oparl-temp:file"))
                (:classification :url ,(s-prefix "org:classification"))
                (:keyword :string ,(s-prefix "oparl-temp:keyword"))
                (:web :url ,(s-prefix "oparl-temp:web"))
                (:deleted :boolean ,(s-prefix "oparl-temp:deleted"))
                (:type :string ,(s-prefix "dct:type"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:show-in-hvt :boolean ,(s-prefix "ext:showInHVT"))
                (:represents :uri ,(s-prefix "euvoc:represents")))
  :has-one `((temporal :via ,(s-prefix "dct:temporal")
                       :as "temporal")
             (location :via ,(s-prefix "oparl-temp:location")
                       :as "location"))
  :has-many `((contactPoint :via ,(s-prefix "schema:contactPoint")
                            :as "contact-points")
              (person :via ,(s-prefix "oparl-temp:person")
                      :as "people")
              (parliamentaryTerm :via ,(s-prefix "org:isLinkedTo")
                                 :as "is-linked-to")
              (foreseenActivity :via ,(s-prefix "oparl-temp:agendaItem")
                                :as "agenda-items")
              (membership :via ,(s-prefix "oparl-temp:membership")
                          :as "memberships")
              (organization :via ,(s-prefix "org:hasSubOrganization")
                           :as "has-sub-organizations")
              (organization :via ,(s-prefix "org:hasSubOrganization")
                           :inverse t
                           :as "sub-organization-of"))
  :resource-base (s-url "http://data.lblod.info/id/organizations/")
  :features '(include-uri)
  :on-path "organizations")

(define-resource person ()
  :class (s-prefix "foaf:Person")
  :properties `((:label :string ,(s-prefix "rdfs:label"))
                (:family-name :string ,(s-prefix "foaf:familyName"))
                (:given-name :string ,(s-prefix "foaf:givenName"))
                (:form-of-address :string ,(s-prefix "oparl-temp:formOfAddress"))
                (:affix :string ,(s-prefix "oparl-temp:affix"))
                (:honorific-prefix :string ,(s-prefix "vcard:hasHonorificPrefix"))
                (:has-gender :url ,(s-prefix "vcard:hasGender"))
                (:phone :string ,(s-prefix "oparl-temp:phone"))
                (:email :string ,(s-prefix "oparl-temp:email"))
                (:status :string ,(s-prefix "oparl-temp:status"))
                (:license :string ,(s-prefix "oparl-temp:license"))
                (:keyword :string ,(s-prefix "oparl-temp:keyword"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:web :url ,(s-prefix "oparl-temp:web"))
                (:deleted :boolean ,(s-prefix "oparl-temp:deleted")))
  :has-one `((organization :via ,(s-prefix "oparl-temp:body")
                           :as "body")
             (location :via ,(s-prefix "oparl-temp:location")
                       :as "location"))
  :has-many `((membership :via ,(s-prefix "org:hasMembership")
                          :as "memberships"))
  :resource-base (s-url "http://data.lblod.info/id/people/")
  :features '(include-uri)
  :on-path "people")

(define-resource contactPoint ()
  :properties `((:name :string ,(s-prefix "foaf:name"))
                (:email :string ,(s-prefix "schema:email"))))

(define-resource temporal ()
  :class (s-prefix "dct:PeriodOfTime")
  :properties `((:start-date :date ,(s-prefix "dcat:startDate"))
                (:end-date :date ,(s-prefix "dcat:endDate")))
  :resource-base (s-url "http://data.lblod.info/id/temporals/"))

(define-resource membership ()
  :class (s-prefix "org:Membership")
  :resource-base (s-url "http://data.lblod.info/id/memberships/"))

(define-resource location-temp ()
  :class (s-prefix "oparl-temp:Location")
  :resource-base (s-url "http://data.lblod.info/id/locations/"))
