(in-package :mu-cl-resources)

(add-prefix "besluit" "http://data.vlaanderen.be/ns/besluit#")
(add-prefix "cms" "http://mu.semte.ch/vocabulary/cms/")
(add-prefix "dcat" "http://www.w3.org/ns/dcat#")
(add-prefix "dct" "http://purl.org/dc/terms/")
(add-prefix "eli" "http://data.europa.eu/eli/ontology#")
(add-prefix "eli-dl" "http://data.europa.eu/eli/eli-draft-legislation-ontology#")
(add-prefix "epvoc" "https://data.europarl.europa.eu/def/epvoc#")
(add-prefix "euvoc" "http://publications.europa.eu/ontology/euvoc#")
(add-prefix "ext" "http://mu.semte.ch/vocabularies/ext/")
(add-prefix "foaf" "http://xmlns.com/foaf/0.1/")
(add-prefix "oparl-temp" "http://mu.semte.ch/vocabularies/ext/oparl/")
(add-prefix "org" "http://www.w3.org/ns/org#")
(add-prefix "rdfs" "http://www.w3.org/2000/01/rdf-schema#")
(add-prefix "schema" "http://schema.org/")
(add-prefix "skos" "http://www.w3.org/2004/02/skos/core#")
(add-prefix "vcard" "http://www.w3.org/2006/vcard/ns#")
(add-prefix "oa" "http://www.w3.org/ns/oa#")
(add-prefix "nif" "http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#")
(add-prefix "hrvst" "http://lblod.data.gift/vocabularies/harvesting/")
(add-prefix "dgftSec" "http://lblod.data.gift/vocabularies/security/")
(add-prefix "wotSec" "https://www.w3.org/2019/wot/security#")
(add-prefix "dgftOauth" "http://kanselarij.vo.data.gift/vocabularies/oauth-2.0-session/")
(add-prefix "geosparql" "http://www.opengis.net/ont/geosparql#")
(add-prefix "locn" "http://www.w3.org/ns/locn#")
(add-prefix "sh" "http://www.w3.org/ns/shacl#")